const fs = require('fs');
const path = require('path');

// Minimal .env parser (no external deps)
function loadDotEnv(filePath){
  const env = {};
  if (!fs.existsSync(filePath)) return env;
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  for (const line of lines){
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq+1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))){
      val = val.slice(1,-1);
    }
    env[key] = val;
  }
  return env;
}

const root = __dirname;
const envFile = path.join(root, '.env');
const env = loadDotEnv(envFile);

// Defaults (safe/public identifiers for Firebase; avoid hardcoding secrets here)
const config = {
  FIREBASE_API_KEY: env.FIREBASE_API_KEY || "AIzaSyBYyJuTAkVPB_65NqSeca6IueMoMO1iPzs",
  FIREBASE_AUTH_DOMAIN: env.FIREBASE_AUTH_DOMAIN || "polars-shack.firebaseapp.com",
  FIREBASE_PROJECT_ID: env.FIREBASE_PROJECT_ID || "polars-shack",
  FIREBASE_STORAGE_BUCKET: env.FIREBASE_STORAGE_BUCKET || "polars-shack.firebasestorage.app",
  FIREBASE_MESSAGING_SENDER_ID: env.FIREBASE_MESSAGING_SENDER_ID || "205388124682",
  FIREBASE_APP_ID: env.FIREBASE_APP_ID || "1:205388124682:web:2b0b1605517e0c6c53c5f3",
  FIREBASE_DATABASE_URL: env.FIREBASE_DATABASE_URL || "https://polars-shack-default-rtdb.firebaseio.com",

  PROXY_SERVER_URL: env.PROXY_SERVER_URL || "https://render-proxy-6x2v.onrender.com",

  // Leave these empty by default; provide via .env if you need JSONBin
  JSONBIN_API_URL: env.JSONBIN_API_URL || "",
  JSONBIN_MASTER_KEY: env.JSONBIN_MASTER_KEY || "",

  ADMIN_PASSWORD_HASH: env.ADMIN_PASSWORD_HASH || "50172b3e278ccc1f2caaac89e2911df21304024b98578c4642af9d340fc73b71",

  GOOGLE_ADSENSE_PUBLISHER_ID: env.GOOGLE_ADSENSE_PUBLISHER_ID || "pub-9156548662984796",
  GOOGLE_ADSENSE_HEADER_SLOT: env.GOOGLE_ADSENSE_HEADER_SLOT || "",
  GOOGLE_ADSENSE_SIDEBAR_SLOT: env.GOOGLE_ADSENSE_SIDEBAR_SLOT || "",
  GOOGLE_ADSENSE_FOOTER_SLOT: env.GOOGLE_ADSENSE_FOOTER_SLOT || ""
};

// Emit env.js for the browser
const out = `// Auto-generated by build.js. Do not edit.
// Values come from .env (or defaults). Avoid putting secrets client-side when possible.
window.__ENV = Object.assign(window.__ENV || {}, ${JSON.stringify(config, null, 2)});
`;

const outPath = path.join(root, 'env.js');
fs.writeFileSync(outPath, out);
console.log(`✅ Generated env.js from ${fs.existsSync(envFile) ? '.env' : 'defaults'} at ${outPath}`);
